version: '3.7'

services:
  correto-11-jdk:
    image: correto-jdk
    container_name: java-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/working
    command: tail -F anything